### ISSUE TITLE
Add support for Blueprint as well as Spring DSL

### ISSUE THREAD

**Issue by bfitzpat** [jboss-fuse/wsdl2rest#18]
This came up during the tooling demo we had on 29-NOV-2017 with Keith.

Currently the utility generates a great Spring config for the REST DSL. But we also need to support the Blueprint DSL for some of our supported runtime platforms. 

Any chance we can get this in for Fuse 7?

**Comment by tdiesler** [comment]
This would best be dealt with by someone who knows blueprint.

**Comment by tdiesler** [comment]
We have these [two test cases](https://github.com/jboss-fuse/wsdl2rest/tree/master/tests/src/test/java/org/jboss/fuse/wsdl2rest/test). Both consume a camel context definition that is generated as part of [generate-test-sources](https://github.com/jboss-fuse/wsdl2rest/blob/master/tests/pom.xml#L79).

To get started with blueprint, I suggest we first come up with respective blueprint descriptors, that are verified elsewhere. I can then translate these into a velocity template and provide the additional cmd line options to the tool.

Testing the generated blueprint descriptors as part of the build, would require an osgi based test module, which would be good to have but not essential. Initially it'd probably be good enough to verify these descriptors elsewhere. Longer term, it'd however need to be done in this project

**Comment by bfitzpat** [comment]
Awesome. Thanks @ffang !!
