### ISSUE TITLE
Generate client proxy instead of using provided bean implementation

### ISSUE THREAD

**Issue by bfitzpat** [jboss-fuse/wsdl2rest#19]
This came up during the tooling demo we had on 29-NOV-2017 with Keith.

Currently the utility can use an optional bean input when generating the REST DSL output. It came up during the meeting that we should just require the WSDL and use a generated client proxy (CXF?) to wrap the existing service in REST terms.

From Keith: 
- Only prerequisite should be a WSDL - no other artifacts (beans, etc.) should be required. We should only ask for the location of the WSDL and the SOAP address (defaulted from WSDL) the user wants to use.
- The utility should automatically generate the client proxy interface and we don't need the bean at all.

Any chance we can get this in for Fuse 7?

**Comment by tdiesler** [comment]
http://camel.apache.org/cxf-proxy-example.html

**Comment by tdiesler** [comment]
Blocked by #37
