### ISSUE TITLE
Separate locations for generated Camel and Java files

### ISSUE THREAD

**Issue by bfitzpat** [jboss-fuse/wsdl2rest#20]
Any chance we can add a command-line option that offers a specific location for the generated Camel XML file vs. the generated source? One single specified output path doesn't quite work when we're trying to put Java code in src/main/java for source and src/main/resources/OSGI-INF or src/main/resources/META-INF/spring for the Camel configuration.

**Comment by tdiesler** [comment]
I'd say the caller should move the generated output to wherever needed. Would this not work?

**Comment by bfitzpat** [comment]
We could definitely move it as an after-step, but it would be nice to have the option to have it generated in the correct location if specified.

**Comment by tdiesler** [comment]
How are you interfacing with the tool? If it is via cmd line options, I'd be reluctant to expose such a redundant config option to the public. If it is via API, we could do this for your convenience.

**Comment by bfitzpat** [comment]
I am calling the tool in code, not via command line options. It would be great to have a convenience method I could call. 

```
Wsdl2Rest tool = new Wsdl2Rest(wsdlLocation, outpath);
tool.setTargetContext(contextpath);
if (!Strings.isEmpty(options.getBeanClassName())) {
	tool.setTargetBean(options.getBeanClassName());
}
if (!Strings.isEmpty(options.getTargetServiceAddress())) {
	URL targetAddressURL = new URL(options.getTargetServiceAddress());
	tool.setTargetAddress(targetAddressURL);
}
tool.process();
```

**Comment by tdiesler** [comment]
ok, lets do this
