### ISSUE TITLE
Fix warning message during assembly

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/wsdl2rest#31]
> [INFO] --- maven-assembly-plugin:2.2-beta-5:single (assembly-directory) @ wsdl2rest-dist ---
> [INFO] Reading assembly descriptor: scripts/assembly-directory.xml
> [WARNING] Cannot include project artifact: org.jboss.fuse.wsdl2rest:wsdl2rest-dist:pom:0.7-SNAPSHOT; it doesn't have an associated file or directory.
> [INFO] Copying files to C:\git\wsdl2rest\dist\target\wsdl2rest-0.7-SNAPSHOT
> [WARNING] Assembly file: C:\git\wsdl2rest\dist\target\wsdl2rest-0.7-SNAPSHOT is not a regular file (it may be a directory). It cannot be attached to the project build for installation or deployment.

**Comment by tdiesler** [comment]
I updated the assemble plugin, which doesn't fix the issue but I don't think its a problem either.

```
[INFO] --- maven-assembly-plugin:3.1.0:single (assembly-directory) @ wsdl2rest-dist ---
[INFO] Reading assembly descriptor: scripts/assembly-directory.xml
[WARNING] The assembly descriptor contains a filesystem-root relative reference, which is not cross platform compatible /
[WARNING] Cannot include project artifact: org.jboss.fuse.wsdl2rest:wsdl2rest-dist:pom:0.7-SNAPSHOT; it doesn't have an associated file or directory.
[INFO] Copying files to /Users/tdiesler/git/wsdl2rest/dist/target/wsdl2rest-0.7-SNAPSHOT
[WARNING] Assembly file: /Users/tdiesler/git/wsdl2rest/dist/target/wsdl2rest-0.7-SNAPSHOT is not a regular file (it may be a directory). It cannot be attached to the project build for installation or deployment.
```

**Comment by apupier** [comment]
might be this use case https://issues.apache.org/jira/browse/MASSEMBLY-628
